CREATE TABLE MODS(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	TEMPLATE_TEXT VARCHAR(100) NOT NULL,
	AFFIX_TYPE INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE MOD_TIERS(
	ID INTEGER NOT NULL PRIMARY KEY,
	MOD INTEGER,
	TIER INTEGER NOT NULL DEFAULT 1,
	ILEVEL INTEGER NOT NULL DEFAULT 1,
	PERCENT DOUBLE NOT NULL DEFAULT 0.0,
	MIN_RANGE INTEGER NOT NULL DEFAULT 1,
	MAX_RANGE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE MODS_BASES(
	MOD INTEGER NOT NULL,
	ITEM_BASE INTEGER NOT NULL
);

ALTER TABLE PUBLIC.MOD_TIERS ADD FOREIGN KEY(MOD) REFERENCES PUBLIC.MODS;
ALTER TABLE PUBLIC.MODS_BASES ADD FOREIGN KEY(MOD) REFERENCES PUBLIC.MODS;
ALTER TABLE PUBLIC.MODS_BASES ADD FOREIGN KEY (ITEM_BASE) REFERENCES PUBLIC.ITEM_BASES;