CREATE TABLE ITEM_TYPES(
	ID INTEGER NOT NULL PRIMARY KEY,
	ITEM_TYPE VARCHAR(100) NOT NULL,
	ITEM_SUBTYPE VARCHAR(100) NOT NULL
);

CREATE TABLE IMPLICIT_MODS(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	TEMPLATE_TEXT VARCHAR(100) NOT NULL,
	MIN_RANGE INTEGER NOT NULL DEFAULT 1,
	MAX_RANGE INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE ITEM_BASES(
	ID INTEGER NOT NULL PRIMARY KEY,
	ITEM_TYPE INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ITEM_IMPLICIT INTEGER,
	REQUIRED_STR INTEGER NOT NULL DEFAULT 0,
	REQUIRED_DEX INTEGER NOT NULL DEFAULT 0,
	REQUIRED_INT INTEGER NOT NULL DEFAULT 0,
	REQUIRED_LEVEL INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE PUBLIC.ITEM_BASES ADD FOREIGN KEY (ITEM_TYPE) REFERENCES PUBLIC.ITEM_TYPES;
ALTER TABLE PUBLIC.ITEM_BASES ADD FOREIGN KEY (ITEM_IMPLICIT) REFERENCES PUBLIC.IMPLICIT_MODS;